### ISSUE TITLE
Understand how it scales

### ISSUE THREAD

**Issue by cscetbon** [tomkerkhove/dapr-actors-sandbox#13]
Hey @tomkerkhove, I'm learning how actors work in Dapr. Do you have a more elaborate description of how the whole architecture works ? I see the architecture diagram but I'm not sure how it scales for instance. Also what happens if the service goes down ? nothing works ? I understand that it registers Actor types but I'm not sure how crucial it is for the architecture.

Thanks

**Comment by tomkerkhove** [comment]
Dapr actors are turn-based and scaling happens through the underlying Dapr actor host, but I recommend reading the [Dapr docs](https://dapr.io/) and ask for more details there

**Comment by cscetbon** [comment]
Yea I've read this and just watched the video where you explain it but was looking for more answers, especially feedback from users. Okay closing this issue.

**Comment by tomkerkhove** [comment]
For what it's worth, I was a customer when I recorded that video :)
